import eventModel from '../models/eventModel.js'
import QRCode from 'qrcode'
import crypto from 'crypto'

/**
 * Automatically generate evaluation QR codes 5 minutes before event end
 */
async function generateEvaluationQRCodes(now) {
    try {
        // Find events that are ending within the next 6 minutes (5 min + 1 min buffer)
        const sixMinutesFromNow = new Date(now.getTime() + 6 * 60 * 1000)
        const fiveMinutesBeforeEnd = new Date(now.getTime() + 5 * 60 * 1000)
        
        const events = await eventModel.find({
            endDate: { 
                $gte: fiveMinutesBeforeEnd, 
                $lte: sixMinutesFromNow 
            },
            status: { $in: ['Approved', 'Upcoming', 'Ongoing'] },
            isOpenForVolunteer: true
        })

        for (const event of events) {
            const eventEnd = new Date(event.endDate)
            const fiveMinutesBefore = new Date(eventEnd.getTime() - (5 * 60 * 1000))
            
            // Only generate if we're within the 5-minute window
            if (now >= fiveMinutesBefore && now <= eventEnd) {
                const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
                
                // Check if evaluation QR already exists for today
                if (!event.qrCodes) {
                    event.qrCodes = []
                }
                
                let qrEntry = event.qrCodes.find(qr => qr.date === todayStr)
                const hasEvaluationQR = qrEntry && qrEntry.checkOut && qrEntry.isActive
                
                if (!hasEvaluationQR) {
                    // Generate evaluation QR code
                    const qrData = {
                        eventId: event._id.toString(),
                        type: 'checkOut',
                        date: todayStr,
                        generatedAt: now.toISOString(),
                        generatedBy: event.createdBy.toString(),
                        random: crypto.randomBytes(16).toString('hex'),
                        autoGenerated: true
                    }
                    
                    const qrString = JSON.stringify(qrData)
                    
                    if (!qrEntry) {
                        qrEntry = {
                            date: todayStr,
                            checkIn: '',
                            checkOut: '',
                            generatedAt: now,
                            generatedBy: event.createdBy,
                            isActive: true,
                            expiresAt: eventEnd
                        }
                        event.qrCodes.push(qrEntry)
                    }
                    
                    qrEntry.checkOut = qrString
                    qrEntry.isActive = true
                    qrEntry.generatedAt = now
                    qrEntry.expiresAt = eventEnd
                    
                    await event.save()
                    console.log(`✅ Auto-generated evaluation QR for event: ${event.title} (${event._id})`)
                }
            }
        }
    } catch (error) {
        console.error('Error in generateEvaluationQRCodes:', error)
    }
}

export async function runQRScheduler() {
    const now = new Date()
    await generateEvaluationQRCodes(now)
}

export function startQRScheduler() {
    runQRScheduler().catch(err => console.error('Initial QR scheduler error', err))
    // Run every minute to catch the 5-minute window accurately
    setInterval(() => {
        runQRScheduler().catch(err => console.error('QR scheduler error', err))
    }, 60 * 1000) // every 1 minute
    console.log('✅ QR code scheduler started (auto-generates evaluation QR 5 min before event end)')
}

